### ISSUE TITLE
ToDo(v1.4.0)

### ISSUE THREAD

**Issue by kexin8** [kexin8/auto-deploy#1]
待办事项（v1.4.0）：

- [ ] fix：修复执行`deploy /path/to/pyconfig.json`命令指定配置文件启动时，如果`srcFile`配置的是相对路径，会提示找不到文件错误（影响范围:  v1.3.0-pre及以下）
- [ ] feat：`deploy init`初始化配置命令支持动态提示
- [ ] feat：支持`dyconfig.json`中配置多个部署单元，支持如`deploy dev`部署服务。例如：
```json
{
  "dev": {
    "address": "devip_port",
    "username": "username",
    "password": "password",
    "srcFile": "file1,file2,...",
    "workDir": "/path/to/workDir",
    "changeWorkDir": true,
    "preCmd": [
      "echo 'preCmds'"
    ],
    "postCmd": [
      "echo 'postCmds'"
    ]
  },
  "test": {
    "address": "testip_port",
    "username": "username",
    "password": "password",
    "srcFile": "file1,file2,...",
    "workDir": "/path/to/workDir",
    "changeWorkDir": true,
    "preCmd": [
      "echo 'preCmds'"
    ],
    "postCmd": [
      "echo 'postCmds'"
    ]
  },
  "prod": {
    "address": "prodip_port",
    "username": "username",
    "password": "password",
    "srcFile": "file1,file2,...",
    "workDir": "/path/to/workDir",
    "changeWorkDir": true,
    "preCmd": [
      "echo 'preCmds'"
    ],
    "postCmd": [
      "echo 'postCmds'"
    ]
  }
}
```
